### ISSUE TITLE
[Win 10/Mac/Linux, Rack2 Pro v2.0.0] Randomizing EV3 crashes Rack

### ISSUE THREAD

**Issue by SteveRussell33** [kockie69/SquinkyVCV-main#52]
Empty Rack, add EV3. Use context menu or Ctrl+R to randomize 3+ times, crash occurs.
Replicated by some users here: https://community.vcvrack.com/t/porting-squinky-labs-to-v2/14210/92
```
Thread 1 received signal SIGSEGV, Segmentation fault.
WaveformSwitch::step (this=0x1abe69e3800) at src/ctrl/WaveformSwitch.h:107
107             cell->setState(true);
(gdb) bt
#0  WaveformSwitch::step (this=0x1abe69e3800) at src/ctrl/WaveformSwitch.h:107
#1  0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#2  0x00007fff26dd21df in EV3Widget::step (this=0x1abdb4f7a70) at src/EV3Module.cpp:333
#3  0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#4  0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#5  0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#6  0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#7  0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#8  0x00007fff359e3c13 in libRack!_ZN4rack2ui12ScrollWidget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#9  0x00007fff359bdd31 in libRack!_ZN4rack3app16RackScrollWidget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#10 0x00007fff359eb8c3 in libRack!_ZN4rack6widget6Widget4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#11 0x00007fff359ee2bc in libRack!_ZN4rack6window6Window4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#12 0x00007fff359eea30 in libRack!_ZN4rack6window6Window3runEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#13 0x00007ff71ac7119f in ?? ()
#14 0x00007ff71ac61a63 in ?? ()
#15 0x00007ff71ac613d4 in ?? ()
#16 0x00007ff71ac614e6 in ?? ()
#17 0x00007fff68cc7034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#18 0x00007fff6a822651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#19 0x0000000000000000 in ?? ()
```
Linux trace
```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f732870a859 in __GI_abort () at abort.c:79
#2  0x0000000000403dc5 in  ()
#3  0x00007f732872b210 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f7324452374 in WaveformSwitch::step() () at /home/cschol/.Rack2/plugins/squinkylabs-plug1/plugin.so
#5  0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#6  0x00007f7324452279 in EV3Widget::step() () at /home/cschol/.Rack2/plugins/squinkylabs-plug1/plugin.so
#7  0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#8  0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#9  0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#10 0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#11 0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#12 0x00007f7328da340f in rack::ui::ScrollWidget::step() () at ./libRack.so
#13 0x00007f7328e2440e in rack::app::RackScrollWidget::step() () at ./libRack.so
#14 0x00007f7328e2bba6 in rack::widget::Widget::step() () at ./libRack.so
#15 0x00007f7328dcb087 in rack::window::Window::step() () at ./libRack.so
#16 0x00007f7328dcb748 in rack::window::Window::run() () at ./libRack.so
#17 0x000000000040386d in main ()
```

**Comment by SteveRussell33** [comment]
Confirming fix https://github.com/kockie69/SquinkyVCV-main/commit/b0a7384c1567bf132cfa87cef80704a2a8fabdb0 is good.

Cheers
